[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'

[tool.isort]
profile = 'black'
line_length = 100
known_first_party = ["Todo_List", "Todo_List_App"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = [".git", "__pycache__", "build", "dist", "*/migrations/*", "venv"]

[tool.mypy]
python_version = "3.12"
plugins = ["mypy_django_plugin.main"]
disallow_untyped_defs = true
ignore_missing_imports = true
exclude = "migrations|venv|env"

[tool.django-stubs]
django_settings_module = "Todo_List.settings"
