apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-namespace

resources:
  - deployment.yaml
  - celery-worker-deployment.yaml
  - celery-beat-deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
commonLabels:
  app: todo-list
