apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-namespace-default
images:
  - name: TODO_IMAGE
    newName: 149681869636.dkr.ecr.eu-central-1.amazonaws.com/todo-list-default
    newTag: latest
resources:
  - ../../base
commonLabels:
  app: todo-list
