name: Todo CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # DB
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_USER: ${{vars.DB_USER}}
      DB_NAME: ${{vars.DB_NAME}}
      DB_PORT: ${{vars.DB_PORT}}
      DB_HOST: ${{vars.DB_HOST}}
      DB_ENGINE: ${{vars.DB_ENGINE}}
      DB_SSL_MODE: ${{vars.DB_SSL_MODE}}
      # Redis
      REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
      REDIS_USE_TLS: ${{vars.REDIS_USE_TLS}}
      REDIS_USERNAME: ${{vars.REDIS_USERNAME}}
      REDIS_PORT: ${{vars.REDIS_PORT}}
      REDIS_HOST: ${{vars.REDIS_HOST}}
      # Django
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      FERNET_KEY: ${{secrets.FERNET_KEY}}
      CELERY_TIMEZONE: ${{vars.CELERY_TIMEZONE}}
      ALLOWED_HOSTS: ${{vars.ALLOWED_HOSTS}}
      CSRF_TRUSTED_ORIGINS: ${{vars.CSRF_TRUSTED_ORIGINS}}
      TIME_ZONE: ${{vars.TIME_ZONE}}
      IS_DEBUG: ${{vars.IS_DEBUG}}
      TODO_BACKEND_PORT: ${{vars.TODO_BACKEND_PORT}}
      # Django super-user
      DJANGO_SUPERUSER_USERNAME: ${{vars.DJANGO_SUPERUSER_USERNAME}}
      DJANGO_SUPERUSER_FIRST_NAME: ${{vars.DJANGO_SUPERUSER_FIRST_NAME}}
      DJANGO_SUPERUSER_LAST_NAME: ${{vars.DJANGO_SUPERUSER_LAST_NAME}}
      DJANGO_SUPERUSER_PASSWORD: ${{vars.DJANGO_SUPERUSER_PASSWORD}}
      # Email settings
      EMAIL_HOST_USER: ${{secrets.EMAIL_HOST_USER}}
      EMAIL_HOST_PASSWORD: ${{secrets.EMAIL_HOST_PASSWORD}}
      EMAIL_BACKEND: ${{vars.EMAIL_BACKEND}}
      EMAIL_HOST: ${{vars.EMAIL_HOST}}
      EMAIL_PORT: ${{vars.EMAIL_PORT}}
      EMAIL_USE_TLS: ${{vars.EMAIL_USE_TLS}}
    services:
      postgres:
        image: postgres:16.9
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{vars.DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          POSTGRES_DB: ${{vars.DB_NAME}}
        options: >-
          --health-cmd="pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:7.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s 
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run code quality checks
        run: pre-commit run --config .pre-commit-config.yaml --all-files
      - name: Check Missing Migrations
        run: python manage.py makemigrations --check
      - name: Run tests
        run: |
          python manage.py migrate
          python manage.py test
      - name: Django --deploy checks
        run: python manage.py check --deploy
      - name: Scan Python dependencies for vulnerabilities
        continue-on-error: true
        run: pip-audit
      - name: Run the server and test it
        run: |
          python manage.py runserver 0.0.0.0:${TODO_BACKEND_PORT} &
          sleep 10
          curl -sSf http://localhost:${TODO_BACKEND_PORT} > /dev/null && echo "Server is Up"

  bootstrap_infra:
    if: github.ref_name == 'main' || github.ref_name == 'develop'
    needs: test
    env:
      # Init Terraform
      TF_VAR_do_token: ${{secrets.TF_VAR_do_token}}
      TF_STG_BACKEND_BUCKET: ${{vars.TF_STG_BACKEND_BUCKET}}
      TF_STG_BOOTSTRAP_BACKEND_KEY: ${{vars.TF_STG_BOOTSTRAP_BACKEND_KEY}}
      TF_STG_APP_INFRA_BACKEND_KEY: ${{vars.TF_STG_APP_INFRA_BACKEND_KEY}}
      TF_STG_BACKEND_REGION: ${{vars.TF_STG_BACKEND_REGION}}
      # S3 config
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      SPACES_ACCESS_KEY_ID: ${{secrets.SPACES_ACCESS_KEY_ID}}
      SPACES_SECRET_ACCESS_KEY: ${{secrets.SPACES_SECRET_ACCESS_KEY}}
      # TF_VAR_
      TF_VAR_registry_name: ${{vars.TF_VAR_registry_name}}
      TF_VAR_container_registry_subscription_plan: ${{vars.TF_VAR_container_registry_subscription_plan}}
      TF_VAR_todo_project_name: ${{vars.TF_VAR_todo_project_name}}
    runs-on: ubuntu-latest
    outputs: # Define outputs for the entire job
      container_reg: ${{ steps.tf_todo_cr.outputs.reg_url }}  # Maps step output to job output
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Init Terraform
        working-directory: terraform/digital_ocean/bootstrap
        run: ./init.sh
      - name: Terraform Plan
        working-directory: terraform/digital_ocean/bootstrap
        run: terraform plan -input=false
      - name: Terraform Apply and Output
        id: tf_todo_cr
        working-directory: terraform/digital_ocean/bootstrap
        run: |
          terraform apply -auto-approve
          echo "reg_url=$(terraform output -raw container_registry_url)" >> $GITHUB_OUTPUT

  docker_build_push:
    if: github.ref_name == 'main' || github.ref_name == 'develop'
    needs: bootstrap_infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Registry login
        run: doctl registry login
      - name: Choosing the right image tag...
        id: image_tag
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "IMAGE_TAG=stable" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_OUTPUT
          fi
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ needs.bootstrap_infra.outputs.container_reg }}/todo:${{ steps.image_tag.outputs.IMAGE_TAG }}
